# Generated by Django 5.2.4 on 2025-08-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_rename_name_product_color_product_model_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fitting_area',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
